const sampleProducts = [
  // ===== EXISTING 4 PRODUCTS (kept as-is) =====
  {
    name: "Velvet Glow Serum",
    description:
      "A lightweight brightening serum that hydrates deeply and leaves skin with a soft radiant finish.",
    brand: "ALANKAAR",
    category: "Skincare",
    image: "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=900&q=80",
    price: 350,
    countInStock: 24,
    rating: 4.8,
    numReviews: 18,
    featured: true,
    skinType: "All Types",
    tags: ["brightening", "hydrating", "serum"],
    gender: "Unisex",
  },
  {
    name: "Rose Cloud Tint",
    description:
      "A buildable cheek and lip tint with a fresh rosy finish designed for comfortable all-day wear.",
    brand: "ALANKAAR",
    category: "Lip Care",
    image: "https://images.unsplash.com/photo-1596462502278-27bfdc403348?auto=format&fit=crop&w=900&q=80",
    price: 280,
    countInStock: 40,
    rating: 4.6,
    numReviews: 11,
    featured: true,
    skinType: "All Types",
    tags: ["lip tint", "cheek tint", "rosy"],
    gender: "Women",
  },
  {
    name: "Luminous Silk Cream",
    description:
      "A rich face cream that supports the skin barrier and gives dry skin a smooth, healthy glow.",
    brand: "ALANKAAR",
    category: "Skincare",
    image: "https://images.unsplash.com/photo-1617897903246-719242758050?auto=format&fit=crop&w=900&q=80",
    price: 320,
    countInStock: 32,
    rating: 4.7,
    numReviews: 14,
    featured: false,
    skinType: "Dry Skin",
    tags: ["moisturiser", "glow", "barrier repair"],
    gender: "Unisex",
  },
  {
    name: "Soft Focus Primer",
    description:
      "A smoothing primer that reduces the look of pores and helps makeup stay fresh for longer.",
    brand: "ALANKAAR",
    category: "Makeup",
    image: "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=900&q=80",
    price: 300,
    countInStock: 20,
    rating: 4.5,
    numReviews: 9,
    featured: false,
    skinType: "Combination Skin",
    tags: ["primer", "pore minimiser", "long wear"],
    gender: "Unisex",
  },

  // ===== HAIR (6 products) =====
  {
    name: "Nourishing Argan Hair Oil",
    description:
      "A lightweight argan-infused oil that tames frizz, adds brilliant shine, and deeply nourishes dry, damaged ends without weighing hair down.",
    brand: "ALANKAAR",
    category: "Body Care",
    image: "https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?auto=format&fit=crop&w=900&q=80",
    price: 449,
    countInStock: 35,
    rating: 4.7,
    numReviews: 28,
    featured: false,
    skinType: "All Types",
    tags: ["argan", "shine", "frizz control"],
    gender: "Women",
  },
  {
    name: "Keratin Repair Shampoo",
    description:
      "A keratin-enriched shampoo that rebuilds damaged hair fibres, restores elasticity, and leaves hair feeling silky smooth after every wash.",
    brand: "ALANKAAR",
    category: "Body Care",
    image: "https://images.unsplash.com/photo-1631729371254-42c2892f0e6e?auto=format&fit=crop&w=900&q=80",
    price: 399,
    countInStock: 42,
    rating: 4.5,
    numReviews: 22,
    featured: false,
    skinType: "All Types",
    tags: ["keratin", "repair", "shampoo"],
    gender: "Unisex",
  },
  {
    name: "Deep Moisture Hair Mask",
    description:
      "An intensive weekly hair mask infused with shea butter and coconut milk that transforms dry, brittle hair into soft, manageable locks.",
    brand: "ALANKAAR",
    category: "Body Care",
    image: "https://images.unsplash.com/photo-1526947425960-945c6e72858f?auto=format&fit=crop&w=900&q=80",
    price: 499,
    countInStock: 20,
    rating: 4.8,
    numReviews: 31,
    featured: true,
    skinType: "All Types",
    tags: ["deep conditioning", "shea butter", "hair mask"],
    gender: "Women",
  },
  {
    name: "Anti-Frizz Hair Serum",
    description:
      "A silicone-free serum that smooths flyaways and controls frizz while adding a natural, healthy-looking shine that lasts all day.",
    brand: "ALANKAAR",
    category: "Body Care",
    image: "https://images.unsplash.com/photo-1519735777090-ec97162dc266?auto=format&fit=crop&w=900&q=80",
    price: 349,
    countInStock: 28,
    rating: 4.4,
    numReviews: 16,
    featured: false,
    skinType: "All Types",
    tags: ["anti-frizz", "shine", "lightweight"],
    gender: "Unisex",
  },
  {
    name: "Volumising Dry Shampoo",
    description:
      "A micro-fine powder spray that absorbs excess oil, adds instant volume and texture, and extends your blowout by up to two days.",
    brand: "ALANKAAR",
    category: "Body Care",
    image: "https://images.unsplash.com/photo-1585751119414-ef2636f8aede?auto=format&fit=crop&w=900&q=80",
    price: 299,
    countInStock: 45,
    rating: 4.3,
    numReviews: 19,
    featured: false,
    skinType: "All Types",
    tags: ["volume", "oil absorbing", "dry shampoo"],
    gender: "Women",
  },
  {
    name: "Men's 2-in-1 Shampoo",
    description:
      "An all-in-one shampoo and conditioner with charcoal and tea tree oil that cleanses deeply, removes build-up, and leaves hair fresh.",
    brand: "ALANKAAR",
    category: "Body Care",
    image: "https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?auto=format&fit=crop&w=900&q=80",
    price: 349,
    countInStock: 38,
    rating: 4.5,
    numReviews: 25,
    featured: false,
    skinType: "All Types",
    tags: ["charcoal", "tea tree", "men"],
    gender: "Men",
  },

  // ===== SKIN / FACE (5 products) =====
  {
    name: "Vitamin C Brightening Serum",
    description:
      "A potent 15% vitamin C serum with hyaluronic acid that fades dark spots, evens skin tone, and delivers a radiant, youthful glow.",
    brand: "ALANKAAR",
    category: "Skincare",
    image: "https://images.unsplash.com/photo-1611930022073-b7a4ba5fcccd?auto=format&fit=crop&w=900&q=80",
    price: 599,
    countInStock: 30,
    rating: 4.9,
    numReviews: 42,
    featured: true,
    skinType: "All Types",
    tags: ["vitamin C", "brightening", "anti-aging"],
    gender: "Women",
  },
  {
    name: "SPF 50 Daily Sunscreen",
    description:
      "A broad-spectrum SPF 50 sunscreen with a lightweight, non-greasy formula that blends seamlessly and protects against UVA and UVB rays.",
    brand: "ALANKAAR",
    category: "Skincare",
    image: "https://images.unsplash.com/photo-1601049676099-e7ed07d825b0?auto=format&fit=crop&w=900&q=80",
    price: 499,
    countInStock: 55,
    rating: 4.6,
    numReviews: 38,
    featured: false,
    skinType: "All Types",
    tags: ["SPF 50", "broad spectrum", "daily wear"],
    gender: "Unisex",
  },
  {
    name: "Hydrating Rose Toner",
    description:
      "A gentle alcohol-free toner with rose water and glycerin that hydrates, soothes redness, and prepares skin for the rest of your routine.",
    brand: "ALANKAAR",
    category: "Skincare",
    image: "https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?auto=format&fit=crop&w=900&q=80",
    price: 349,
    countInStock: 40,
    rating: 4.5,
    numReviews: 20,
    featured: false,
    skinType: "Dry Skin",
    tags: ["rose water", "hydrating", "alcohol-free"],
    gender: "Women",
  },
  {
    name: "Men's Oil Control Face Wash",
    description:
      "A deep-cleansing face wash with salicylic acid and neem extract that controls excess oil, unclogs pores, and prevents breakouts.",
    brand: "ALANKAAR",
    category: "Skincare",
    image: "https://images.unsplash.com/photo-1608248563723-1d9b1c78913a?auto=format&fit=crop&w=900&q=80",
    price: 299,
    countInStock: 50,
    rating: 4.4,
    numReviews: 15,
    featured: false,
    skinType: "Oily Skin",
    tags: ["oil control", "salicylic acid", "men"],
    gender: "Men",
  },
  {
    name: "Men's Daily Moisturiser",
    description:
      "A fast-absorbing, non-sticky moisturiser with aloe vera and vitamin E that hydrates and protects skin throughout the day.",
    brand: "ALANKAAR",
    category: "Skincare",
    image: "https://images.unsplash.com/photo-1612817288484-6f916006741a?auto=format&fit=crop&w=900&q=80",
    price: 349,
    countInStock: 35,
    rating: 4.3,
    numReviews: 12,
    featured: false,
    skinType: "Normal Skin",
    tags: ["aloe vera", "vitamin E", "daily care"],
    gender: "Men",
  },

  // ===== BODY (5 products) =====
  {
    name: "Shea Butter Body Lotion",
    description:
      "A rich, deeply hydrating body lotion with pure shea butter and jojoba oil that softens rough skin and locks in moisture for 24 hours.",
    brand: "ALANKAAR",
    category: "Body Care",
    image: "https://images.unsplash.com/photo-1608248597279-f99d160bfcbc?auto=format&fit=crop&w=900&q=80",
    price: 399,
    countInStock: 48,
    rating: 4.6,
    numReviews: 27,
    featured: false,
    skinType: "Dry Skin",
    tags: ["shea butter", "24hr hydration", "body care"],
    gender: "Women",
  },
  {
    name: "Coffee Body Scrub",
    description:
      "An invigorating body scrub with ground arabica coffee and coconut oil that exfoliates dead skin, boosts circulation, and leaves skin silky smooth.",
    brand: "ALANKAAR",
    category: "Body Care",
    image: "https://images.unsplash.com/photo-1570194065650-d99fb4b38b17?auto=format&fit=crop&w=900&q=80",
    price: 449,
    countInStock: 22,
    rating: 4.7,
    numReviews: 33,
    featured: false,
    skinType: "All Types",
    tags: ["coffee", "exfoliating", "coconut oil"],
    gender: "Unisex",
  },
  {
    name: "Refreshing Body Wash",
    description:
      "A gentle, sulfate-free body wash with cucumber and green tea extracts that cleanses without stripping, leaving skin refreshed and lightly scented.",
    brand: "ALANKAAR",
    category: "Body Care",
    image: "https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?auto=format&fit=crop&w=900&q=80",
    price: 299,
    countInStock: 60,
    rating: 4.4,
    numReviews: 18,
    featured: false,
    skinType: "All Types",
    tags: ["sulfate-free", "cucumber", "refreshing"],
    gender: "Unisex",
  },
  {
    name: "24Hr Deodorant Roll-On",
    description:
      "A long-lasting roll-on deodorant with natural mineral salts that neutralises odour for up to 24 hours without blocking pores.",
    brand: "ALANKAAR",
    category: "Body Care",
    image: "https://images.unsplash.com/photo-1585386959984-a4155224a1ad?auto=format&fit=crop&w=900&q=80",
    price: 199,
    countInStock: 55,
    rating: 4.2,
    numReviews: 14,
    featured: false,
    skinType: "All Types",
    tags: ["24hr protection", "roll-on", "mineral"],
    gender: "Unisex",
  },
  {
    name: "Luxury Perfume Mist",
    description:
      "A sophisticated body mist with notes of jasmine, vanilla, and white musk that leaves a delicate, lasting fragrance for any occasion.",
    brand: "ALANKAAR",
    category: "Fragrance",
    image: "https://images.unsplash.com/photo-1541643600914-78b084683601?auto=format&fit=crop&w=900&q=80",
    price: 799,
    countInStock: 18,
    rating: 4.8,
    numReviews: 45,
    featured: false,
    skinType: "All Types",
    tags: ["jasmine", "vanilla", "luxury fragrance"],
    gender: "Women",
  },

  // ===== MEN GROOMING (5 products) =====
  {
    name: "Beard Growth Oil",
    description:
      "A nourishing blend of argan, jojoba, and vitamin E oils that promotes thicker beard growth, softens coarse hair, and reduces itchiness.",
    brand: "ALANKAAR",
    category: "Body Care",
    image: "https://images.unsplash.com/photo-1621607512214-68297480165e?auto=format&fit=crop&w=900&q=80",
    price: 449,
    countInStock: 30,
    rating: 4.6,
    numReviews: 35,
    featured: false,
    skinType: "All Types",
    tags: ["beard growth", "argan oil", "anti-itch"],
    gender: "Men",
  },
  {
    name: "Matte Finish Beard Balm",
    description:
      "A styling beard balm with beeswax and shea butter that tames flyaways, provides a natural matte hold, and conditions facial hair.",
    brand: "ALANKAAR",
    category: "Body Care",
    image: "https://images.unsplash.com/photo-1621607505762-49ee8cee60ff?auto=format&fit=crop&w=900&q=80",
    price: 399,
    countInStock: 25,
    rating: 4.4,
    numReviews: 18,
    featured: false,
    skinType: "All Types",
    tags: ["matte hold", "beeswax", "beard styling"],
    gender: "Men",
  },
  {
    name: "Sensitive Skin Shaving Cream",
    description:
      "A rich, cushioning shaving cream with aloe vera and chamomile that provides a close, comfortable shave without irritation or razor burn.",
    brand: "ALANKAAR",
    category: "Body Care",
    image: "https://images.unsplash.com/photo-1585747860019-8e79b4b73212?auto=format&fit=crop&w=900&q=80",
    price: 349,
    countInStock: 40,
    rating: 4.5,
    numReviews: 22,
    featured: false,
    skinType: "Sensitive Skin",
    tags: ["sensitive skin", "aloe vera", "no razor burn"],
    gender: "Men",
  },
  {
    name: "Cool Splash After Shave",
    description:
      "A cooling, alcohol-free aftershave splash with menthol and witch hazel that soothes freshly shaved skin, reduces redness, and prevents ingrown hairs.",
    brand: "ALANKAAR",
    category: "Body Care",
    image: "https://images.unsplash.com/photo-1594035910387-fea47794261f?auto=format&fit=crop&w=900&q=80",
    price: 299,
    countInStock: 35,
    rating: 4.3,
    numReviews: 15,
    featured: false,
    skinType: "All Types",
    tags: ["cooling", "alcohol-free", "menthol"],
    gender: "Men",
  },
  {
    name: "Men's SPF 30 Sunscreen",
    description:
      "A matte-finish sunscreen designed for men that provides SPF 30 protection, controls oil, and works well under facial hair without leaving white residue.",
    brand: "ALANKAAR",
    category: "Skincare",
    image: "https://images.unsplash.com/photo-1601049676099-e7ed07d825b0?auto=format&fit=crop&w=900&q=80",
    price: 449,
    countInStock: 30,
    rating: 4.5,
    numReviews: 20,
    featured: false,
    skinType: "All Types",
    tags: ["SPF 30", "matte finish", "oil control"],
    gender: "Men",
  },

  // ===== MAKEUP / WELLNESS (4 products) =====
  {
    name: "Matte Nude Lipstick",
    description:
      "A velvety matte lipstick in a universally flattering nude shade that delivers full pigment in a single swipe and lasts up to 8 hours.",
    brand: "ALANKAAR",
    category: "Lip Care",
    image: "https://images.unsplash.com/photo-1586495777744-4413f21062fa?auto=format&fit=crop&w=900&q=80",
    price: 499,
    countInStock: 45,
    rating: 4.7,
    numReviews: 40,
    featured: true,
    skinType: "All Types",
    tags: ["matte", "nude shade", "long-lasting"],
    gender: "Women",
  },
  {
    name: "Waterproof Kajal",
    description:
      "A smudge-proof, waterproof kajal pencil with intense black pigment that glides on smoothly and defines eyes for up to 12 hours.",
    brand: "ALANKAAR",
    category: "Makeup",
    image: "https://images.unsplash.com/photo-1631214500115-598fc2cb8ada?auto=format&fit=crop&w=900&q=80",
    price: 249,
    countInStock: 50,
    rating: 4.6,
    numReviews: 32,
    featured: false,
    skinType: "All Types",
    tags: ["waterproof", "smudge-proof", "intense black"],
    gender: "Women",
  },
  {
    name: "Nail Polish Berry Red",
    description:
      "A chip-resistant, glossy nail polish in a rich berry red that applies evenly, dries quickly, and maintains its shine for up to 7 days.",
    brand: "ALANKAAR",
    category: "Makeup",
    image: "https://images.unsplash.com/photo-1604654894610-df63bc536371?auto=format&fit=crop&w=900&q=80",
    price: 199,
    countInStock: 55,
    rating: 4.3,
    numReviews: 15,
    featured: false,
    skinType: "All Types",
    tags: ["berry red", "chip-resistant", "glossy"],
    gender: "Women",
  },
  {
    name: "Gentle Makeup Remover",
    description:
      "A dual-phase makeup remover with micellar technology that effortlessly dissolves waterproof makeup while being gentle on sensitive skin and eyes.",
    brand: "ALANKAAR",
    category: "Skincare",
    image: "https://images.unsplash.com/photo-1596755389378-c31d21fd1273?auto=format&fit=crop&w=900&q=80",
    price: 349,
    countInStock: 38,
    rating: 4.5,
    numReviews: 21,
    featured: false,
    skinType: "Sensitive Skin",
    tags: ["micellar", "gentle", "waterproof removal"],
    gender: "Unisex",
  },
];

export default sampleProducts;
